volumes:
  valkey:

services:
  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    read_only: true
    restart: unless-stopped
    command: >
      valkey-server
      --save 86400 1
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --stop-writes-on-bgsave-error no
    volumes:
      - valkey:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  unbound:
    image: klutchell/unbound
    healthcheck:
      # Use the drill wrapper binary to reduce the exit codes to 0 or 1 for healthchecks
      test: ['CMD', 'drill-hc', '@127.0.0.1', 'dnssec.works']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ./custom.conf.d:/etc/unbound/custom.conf.d:ro
    restart: unless-stopped
    depends_on:
      - valkey
