name: ci

on:
  push:
    tags:
      - "*"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      working_directory: .
      cache_from: |
        docker.io/klutchell/unbound:main
        ghcr.io/klutchell/unbound:main
        docker.io/klutchell/unbound:latest
        ghcr.io/klutchell/unbound:latest
      images: |
        docker.io/klutchell/unbound
        ghcr.io/klutchell/unbound
      platforms: |
        linux/amd64
        linux/arm64
        linux/arm/v7
        linux/arm/v6
      publish: true
      dockerhub_description_repo: klutchell/unbound
