name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    tags:
      - '*.*.*'
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@7d7f4546307e35ff5c07f7859ae010fac8d6e873 # v23.0.19
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      DOCKERHUB_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_REGISTRY_PASS }}
    with:
      disable_versioning: true
      docker_images: |
        ghcr.io/klutchell/unbound,
        klutchell/unbound
      toggle_auto_merge: false
      docker_runs_on: >
        {
          "linux/amd64": ["ubuntu-24.04"],
          "linux/arm64": ["ubuntu-24.04-arm"],
          "linux/arm/v7": ["ubuntu-24.04-arm"],
          "linux/arm/v6": ["ubuntu-24.04-arm"]
        }
